### ISSUE TITLE
Documentación del README y mejora del perfil comunitario del proyecto (Community Standards) 

### ISSUE THREAD

**Issue by miguelms95** [Arquisoft/InciManager_e3b#1]
Escribir archivo README con los autores y el funcionamiento de la aplicación.

**Comment by kilianpg** [comment]
[About community profiles for public repositories](https://help.github.com/articles/about-community-profiles-for-public-repositories)

**Comment by kilianpg** [comment]
Referencias:
- Contributor Covenant: _[Código de Conducta Convenido Para Contribuyentes](https://www.contributor-covenant.org/es/version/1/4/code-of-conduct.html)_

**Comment by kilianpg** [comment]
Referencias;

- GitHub Help: _[Setting guidelines for repository contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)_

**Comment by kilianpg** [comment]
Hecho.

Ya cumplimos 5/6 del [perfil comunitario del proyecto](https://github.com/Arquisoft/InciManager_e3b/community).
