### ISSUE TITLE
Implementar el envío de incidencias mediante formulario web

### ISSUE THREAD

**Issue by kilianpg** [Arquisoft/InciManager_e3b#24]
Kilian, edito el post. Para esta nueva incidencia.

**Comment by miguelms95** [comment]
Están comentados los TODOs de la función del IncidenceController:
```
@RequestMapping(value = "/incidences/add", method = RequestMethod.POST)
    public String addIncidenceFormulario(@ModelAttribute Incidence incidence) {

```
Lo que hay que hacer:
1. Completar el formulario html con los parámetros que faltan de incidencia.
2. Pedir los parámetros por @ RequestParam <- más viable
3. Hacer un parser de la lista de etiquetas, porque la de comentarios y "otros" deberían rellarlos los operarios. Separar por comas y pasarlas a la nueva incidencia que se crea.

**Comment by TonyMarin** [comment]
Se ha implementado el método addIncidenceFormulario en la clase incidenceController y añadido los parámetros necesarios en el formulario HTML
