### ISSUE TITLE
Error al dejar sin cubrir algún campo del formulario

### ISSUE THREAD

**Issue by TonyMarin** [Arquisoft/InciManager_e3b#32]
Cuando intentas insertar alguna incidencia, saltará un error al dejar algún campo del formulario vacío. 
Esto no debería pasar con inputs no obligatorios como pueden ser los campos "others" o "fields"

**Comment by miguelms95** [comment]
Se puede hacer con un validator (más elegante pero lento), o directamente que si hay error mande a una nueva página html de error.

**Comment by Gemeto** [comment]
Ya se pueden dejar en blanco los campos "others" y "fields" sin que salte error.
