### ISSUE TITLE
Incorporar ficheros en la incidencia

### ISSUE THREAD

**Issue by AndresAngelGG** [Arquisoft/InciManager_e3b#36]
Ofrecer al usuario la posibilidad de adjuntar 1 o varios ficheros adjuntos cuando introduce una incidencia en el sistema.
Algo similar a las entregas en el campus virtual, que permita al usuario enviar ficheros.

**Comment by miguelms95** [comment]
¿Por qué? ¿Esto es requisito del módulo? Que yo vea no...

Y en todo caso ya está solucionado con la lista `set<String> others` en Incidence, donde se pueden poner campos relativos a fotos y videos (urls). No vamos a añadir un sistema de subida de ficheros si ya está solucionado, no hay que hacer por hacer, digo yo...
