### ISSUE TITLE
Añadir Codecov

### ISSUE THREAD

**Issue by miguelms95** [Arquisoft/InciManager_e3b#6]
Añadir botón de codecov (https://codecov.io/) en el readme como en proyectos anteriores

**Comment by miguelms95** [comment]
Hola Labra, necesitamos tu ayuda, en [https://codecov.io/gh/Arquisoft/InciManager_e3b](https://codecov.io/gh/Arquisoft/InciManager_e3b) no se ve nada del codecov, en el botón del Readm pone "unknown", pero sí aparece en [logs]( https://codecov.io/gh/Arquisoft/InciManager_e3b/settings/logs) que está integrado
`Mar 14 19:15:02 [INFO] INFO Integration installed {"audit":"t","public":"t","service":"gh","slug":"Arquisoft\/InciManager_e3b","source":"webhook"}` 

¿Alguna sugerencia?

**Comment by labra** [comment]
Os faltaba añadir jacoco en los plugins de Maven en el pom.xml. Lo he añadido y ya tenéis vuestro informe de codecov funcionando.

**Comment by labra** [comment]
Cerré el issue, pero casi mejor os lo dejo abierto y decidís cerrarlo vosotros si lo véis conveniente.

**Comment by miguelms95** [comment]
Vemos conveniente cerrarlo, problema solucionado, gracias 👍🏼
